openshift/cluster-kube-descheduler-operator

deploy/operator.yaml

This should fix the descheduler issue:
`E1123 08:56:08.384453       1 reflector.go:205] github.com/openshift/descheduler-operator/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1alpha1.Descheduler: v1alpha1.DeschedulerList.Items: []v1alpha1.Descheduler: v1alpha1.Descheduler.Spec: v1alpha1.DeschedulerSpec.Strategies: []string: ReadString: expects " or n, but found {, error found in #10 byte of ...|tegies":[{"name":"lo|..., bigger context ...|8-11e8-835e-0e6542778c90"},"spec":{"strategies":[{"name":"lownodeutilization","params":[{"name":"cpu|...`

Fix image location

---

hack/run-e2e.sh

Wanted to test e2e, so I am removing the kubeconfig now, to test, if we are running e2e

Fix e2e tests kubeconfig path

---

README.md

operator-sdk started using role and role_binding. We should start using them instead of single rbac.yaml

Update readme with role and role binding

---

Makefile
pkg/controller/descheduler/descheduler_controller.go

- Makes descheduler to run as critical pod 
- Improves godoc 
- Includes race while testing.
/cc @sjenning

Small fixes and make descheduler pod to run as critical pod

---

pkg/controller/descheduler/descheduler_controller.go

This is to reduce API calls, when desired state and current state are same.
/cc @sjenning

Do not update status when not needed

---

pkg/apis/descheduler/v1alpha1/descheduler_types.go
pkg/controller/descheduler/descheduler_controller.go
test/e2e/descheduler_test.go

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1666649
As of now, we are not exposing the information related to descheduler image being managed by operator, this PR should help in fixing it.
/cc @sjenning

Expose image to be managed by descheduler operator

---

README.md

Descheduler is being installed in `openshift-operators` namespace
(it doesn't seem to be configurable), so an example CRD should use that.
Without namespace set the error message is "Not Found", which is not
helping much

Set namespace in README example

---

Dockerfile
Dockerfile.rhel7
Makefile
OWNERS
README.md
build/Dockerfile
cmd/manager/main.go
pkg/apis/addtoscheme_descheduler_v1alpha1.go
pkg/controller/add_descheduler.go
pkg/controller/descheduler/descheduler_controller.go
pkg/controller/descheduler/descheduler_controller_test.go
test/e2e/descheduler_test.go

With the repo name change, CI is failing. I have a PR to update the CI here: https://github.com/openshift/release/pull/6776 and this will need to be passed through to our current build

Rename references to descheduler-operator package

---

README.md
manifests/0000_00_kube-descheduler-operator.crd.yaml
pkg/apis/descheduler/v1beta1/types_descheduler.go
pkg/apis/descheduler/v1beta1/zz_generated.deepcopy.go
pkg/operator/target_config_reconciler.go

https://github.com/openshift/cluster-kube-descheduler-operator/pull/66 accidentally removed the ability to pass additional descheduler flags to the pod (see options here: https://github.com/kubernetes-sigs/descheduler/blob/30d05382b6e6fc40c8ecc38aedd23918d8eed849/cmd/descheduler/app/options/options.go#L51-L60).
This also replaces the parsing/validating code with just a string list of flags, which are immediately passed to the descheduler pod. Any invalid flags will raise an error when the descheduler runs anyway, so I don't think we need to be responsible for validating them.

Bug 1798220: Re-enable ability to pass additional flags to descheduler pod

---

README.md
manifests/0000_00_kube-descheduler-operator.crd.yaml
manifests/02_kube-descheduler-operator.cr.yaml
pkg/apis/descheduler/v1beta1/types_descheduler.go
pkg/operator/operatorclient/interfaces.go
pkg/operator/starter.go
pkg/operator/target_config_reconciler.go

#66 merged without actually checking any valid value against the expected generation of the deployment. This implements the necessary interfaces to use library-go helpers to update the operator status with the generation information, and uses the information to check against when updating the deployment.

Bug 1798497: Update deployment generation statuses

---

pkg/operator/target_config_reconciler.go

This line was lost when merging https://github.com/openshift/cluster-kube-descheduler-operator/pull/69 and breaks the descheduler deployment

Bug 1799026: Re-add line to dynamically name the deployment policy configmap

---

Dockerfile.rhel7

ART relies on the presence of `com.redhat.delivery.appregistry` label to identify it as an OLM operator.

bug 1803139: Add appregistry delivery label to Dockerfile.rhel7

---

manifests/4.4/image-references

Cherry-picking https://github.com/openshift/cluster-kube-descheduler-operator/pull/85 by hand so we don't need to wait for the next 2 hours for #85 to get merged.

[release-4.4] bug 1805794: Doozer requires spec.tags[].name to be dist-git names

---

manifests/4.4/image-references

Since https://github.com/openshift/ocp-build-data/blob/openshift-4.4/images/atomic-openshift-descheduler.yml#L26
changes the name from atomic-openshift-descheduler to just descheduler.

image-references: descheduler is the right name for the image

---

manifests/4.4/image-references

Backporting https://github.com/openshift/cluster-kube-descheduler-operator/pull/88
Since https://github.com/openshift/ocp-build-data/blob/openshift-4.4/images/atomic-openshift-descheduler.yml#L26
changes the name from atomic-openshift-descheduler to just descheduler.

[release-4.4] bug 1805794: Descheduler image back to descheduler 4.4

---

manifests/4.4/cluster-kube-descheduler-operator.v4.4.0.clusterserviceversion.yaml

Based on https://github.com/operator-framework/operator-courier/blob/master/operatorcourier/validate.py#L580 the following categories are valid:
- "AI/Machine Learning",
- "Application Runtime",
- "Big Data",
- "Cloud Provider",
- "Developer Tools",
- "Database",
- "Integration & Delivery",
- "Logging & Tracing",
- "Monitoring",
- "Networking",
- "OpenShift Optional",
- "Security",
- "Storage",
- "Streaming & Messaging"
"OpenShift Optional" is the closest valid category for the descheduler.

Set the CSV category to OpenShift Optional

---

manifests/4.4/cluster-kube-descheduler-operator.v4.4.0.clusterserviceversion.yaml

Based on https://github.com/operator-framework/operator-courier/blob/master/operatorcourier/validate.py#L580 the following categories are valid:
- "AI/Machine Learning",
- "Application Runtime",
- "Big Data",
- "Cloud Provider",
- "Developer Tools",
- "Database",
- "Integration & Delivery",
- "Logging & Tracing",
- "Monitoring",
- "Networking",
- "OpenShift Optional",
- "Security",
- "Storage",
- "Streaming & Messaging"
"OpenShift Optional" is the closest valid category for the descheduler.
Cherry pick of https://github.com/openshift/cluster-kube-descheduler-operator/pull/90

[release-4.4] bug 1805794: Set the CSV category to OpenShift Optional

---

manifests/4.4/cluster-kube-descheduler-operator.v4.4.0.clusterserviceversion.yaml

Add .0 at the end of the csv name so the name matches clusterkubedescheduleroperator.v{MAJOR}.{MINOR}.0 regex in art.yaml

bug 1810035: csv: change name to clusterkubedescheduleroperator.v4.4.0

---

manifests/4.4/cluster-kube-descheduler-operator.v4.4.0.clusterserviceversion.yaml

Add .0 at the end of the csv name so the name matches clusterkubedescheduleroperator.v{MAJOR}.{MINOR}.0 regex in art.yaml
Cherry-pick of https://github.com/openshift/cluster-kube-descheduler-operator/pull/92

bug 1810033: csv: change name to clusterkubedescheduleroperator.v4.4.0

---

README.md
pkg/operator/target_config_reconciler.go

Fixes https://github.com/openshift/cluster-kube-descheduler-operator/issues/83
This will add support to enable descheduler strategies by their actual documented upstream names, which should alleviate confusion and necessary documentation

Add support for actual descheduler strategy names in operator config

---

Dockerfile

These changes fail to build in Docker with the following error: 
```
Sending build context to Docker daemon  99.73MB
Step 1/10 : FROM registry.svc.ci.openshift.org/openshift/release:golang-1.13 AS builder
golang-1.13: Pulling from openshift/release
ab5ef0e58194: Pull complete 
301c90ab1c95: Pull complete 
Digest: sha256:b78a902936aabab4407529efcd1ca492956efe36de31dc1e16e53bb4b699111f
Status: Downloaded newer image for registry.svc.ci.openshift.org/openshift/release:golang-1.13
---> 3d233cfdbcdc
Step 2/10 : WORKDIR /go/src/github.com/openshift/cluster-kube-descheduler-operator
---> Running in 20283a17dd62
Removing intermediate container 20283a17dd62
---> ea70021478fe
Step 3/10 : COPY . .
---> aef454209edd
Step 4/10 : RUN rm manifests/4*/image-references
---> Running in 8887c0bed92b …
```

Revert changes to dockerfile

---

README.md
deploy/0000_00_kube-descheduler-operator.crd.yaml
deploy/01_namespace.yaml
deploy/02_clusterrole.yaml
deploy/02_kube-descheduler-operator.cr.yaml
deploy/03_clusterrolebinding.yaml
deploy/04_serviceaccount.yaml
deploy/05_deployment.yaml
deploy/05_kube-system-rolebinding.yaml

Until we are able to generate all the manifests from the bundle.

Provide manifests for deploying the operator without OLM (for development only)

---

README.md
pkg/operator/target_config_reconciler.go

This commit was missing from https://github.com/openshift/cluster-kube-descheduler-operator/pull/104

[release-4.4] Bug 1817318: Add support for actual descheduler strategy names in operator config

---

manifests/4.5/cluster-kube-descheduler-operator.v4.5.0.clusterserviceversion.yaml
manifests/4.5/image-references
manifests/4.5/kube-descheduler-operator.crd.yaml
manifests/4.5/kube-system-rolebinding.yaml
manifests/cluster-kube-descheduler-operator.package.yaml
version/version.go

Based on:
```
Error Reported
--------------
ose-cluster-kube-descheduler-operator: file does not exist: /mnt/XXX/ose-cluster-kube-descheduler-operator/manifests/4.5/image-references
```
Mimicking changes in https://github.com/openshift/sriov-network-operator/pull/154
- bumping package version to 4.5
- cloning 4.4 manifests into 4.5

bug 1827169: Bump master to version 4.5

---

pkg/operator/operatorclient/interfaces.go
pkg/operator/target_config_reconciler.go

When the operator configuration is deployed in different namespace than `openshift-kube-descheduler-operator`,
the operator is reporting:
```
E0825 23:53:11.641464       1 target_config_reconciler.go:307] key failed with : kubedeschedulers.operator.openshift.io "cluster" not found
```
The log does not say anything about the namespace.
Explicitly mentioning the expected namespace may give user more hints on what's wrong.

bug 1879139: Be more verbose when the operator configuration is missing

---

manifests/4.6/cluster-kube-descheduler-operator.v4.6.0.clusterserviceversion.yaml

With permissions taken from upstream: https://github.com/kubernetes-sigs/descheduler/blob/release-1.19/kubernetes/rbac.yaml#L20-L22

Bug 1879975: Move priorityclasses to correct apiGroup in SA

---

pkg/operator/target_config_reconciler.go
pkg/operator/target_config_reconciler_test.go

Before the fix:
```
E0923 05:32:54.844907       1 target_config_reconciler.go:467] key failed with : strconv.Atoi: parsing "priorityclass1": invalid syntax
```

bug 1881869: LowNodeUtilization: don't Atoi thresholdPriority params as other params

---

Dockerfile.rhel7

Updating ose-cluster-kube-descheduler-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-cluster-kube-descheduler-operator.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.

Updating ose-cluster-kube-descheduler-operator builder & base images to be consistent with ART

---

manifests/4.4/cluster-kube-descheduler-operator.v4.4.0.clusterserviceversion.yaml
manifests/4.5/cluster-kube-descheduler-operator.v4.5.0.clusterserviceversion.yaml
manifests/4.6/cluster-kube-descheduler-operator.v4.6.0.clusterserviceversion.yaml
manifests/4.7/cluster-kube-descheduler-operator.v4.7.0.clusterserviceversion.yaml

When major, minor, and patch are equal, a pre-release version has lower precedence than a normal version so 4.6.0-202010061132.p0 < 4.6.0.
Because of this, the solver is confused by this and adds the this version into `replaces` field so we end up with the situation that this version is replacing itself.
As a result, the CSV is stuck in Pending state.

bug 1887740: Extend olm.skipRange check to properly compare pre-release versions

---

bindata/v4.1.0/kube-descheduler/deployment.yaml
pkg/operator/v410_00_assets/bindata.go

"failed to validate server configuration" err="unsupported log format: "

bug 1903188: Set --logging-format to text, empty value generates an error message

---

manifests/4.8/kube-descheduler-operator.crd.yaml
pkg/apis/descheduler/v1/types_descheduler.go
pkg/apis/descheduler/v1beta1/types_descheduler.go

To allow CRD's status to be updated

bug 1948640: CRD: add missing subresources.status so the CRD's status can be updated

---

bindata/v4.1.0/kube-descheduler/servicemonitor.yaml
pkg/operator/v410_00_assets/bindata.go

The namespace label is reserved label (see
https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#alertmanagerendpoints).
So the namespace label (indicating from which namespace a pod got
evicted) is automatically relabeled into exported_namespace.
To avoid confusion of what the label means, relabel it into
pod_namespace.
Metrics entry before:
```
descheduler_pods_evicted{endpoint="https", exported_namespace="test1", instance="10.129.3.136:10258", job="metrics", namespace="openshift-kube-descheduler-operator", pod="cluster-85df694595-blktt", result="success", service="metrics", strategy="RemoveDuplicatePods"}
```
Metrics entry after:
```
descheduler_pods_evicted{endpoint="https", exported_namespace="test1", instance="10.129.3.136:10258", job="metrics",  …
```

bug 1949972: servicemonitor: replace exported_namespace with pod_namespace

---

manifests/4.7/cluster-kube-descheduler-operator.v4.7.0.clusterserviceversion.yaml
manifests/4.8/cluster-kube-descheduler-operator.v4.8.0.clusterserviceversion.yaml

Follow up to https://github.com/openshift/cluster-kube-descheduler-operator/pull/177, this removes the dev pattern from the lower version numbers in the CSVs

Bug 1943224: Update olmSkipRange in 4.7 and 4.8 to remove dev pattern

---

README.md
bindata/v4.1.0/profiles/DevPreviewLongLifecycle.yaml
manifests/4.8/kube-descheduler-operator.crd.yaml
pkg/apis/descheduler/v1/types_descheduler.go
pkg/operator/target_config_reconciler.go
pkg/operator/v410_00_assets/bindata.go

Re: https://issues.redhat.com/browse/WRKLDS-286
This adds a new Beta profile `BetaLongLifecycle` which is similar to `LifecycleAndUtilization` but which does not evict running pods that exceed the latter's 24-hour lifetime limit.

Bug 1955595: Add DevPreviewLongLifecycle profile

---

deploy/02_clusterrole.yaml

Updating to copy the changes from https://github.com/openshift/cluster-kube-descheduler-operator/commit/1a022bab559d982c238aee17d78bf555dd9bcc55#

Bug 1959177: Update dev clusterrole manifest

---

manifests/4.9/cluster-kube-descheduler-operator.v4.9.0.clusterserviceversion.yaml

The OperatorHub currently assumes x86-only for any operators which do
not declare any such labels.  Declaring these explicitly should make the
current status more obvious in the code, and make it easier to correctly
add further architectures when conditions warrant.

Bug 1987136: Declare supported arches in CSV

---

bindata/assets/profiles/DoNotEvictPodsWithPVC.yaml
bindata/assets/profiles/EvictPodsWithLocalStorage.yaml
manifests/4.9/kube-descheduler-operator.crd.yaml
pkg/apis/descheduler/v1/types_descheduler.go

Adds profiles which will enable these options in the descheduler policy
ref: https://issues.redhat.com/browse/WRKLDS-304

Bug 1989724: Add Profiles to evict localStorage pods/ignore PVC pods

---

deploy/0000_00_kube-descheduler-operator.crd.yaml
deploy/02_clusterrole.yaml
deploy/05_deployment.yaml
manifests/4.9/cluster-kube-descheduler-operator.v4.9.0.clusterserviceversion.yaml
pkg/operator/starter.go
pkg/operator/target_config_reconciler.go

Fixes error caused by https://github.com/openshift/cluster-kube-descheduler-operator/pull/202, which forgot to start the new informer and add permissions for the `scheduler.config.openshift.io` API group

Bug 1990603: Fix unable to find scheduler config

---

manifests/4.8/kube-descheduler-operator.crd.yaml

Given 4.9 removes v1beta1 version, the OLM complains with
"CRD removes version v1beta1 that is listed as a stored version on the existing CRD".
Based on https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#overview
we need to set served=false in v1beta1 version before it can be removed.

bug 1992478: Set served=false for v1beta1 crd

---

README.md
bindata/assets/profiles/EvictPodsWithPVC.yaml
manifests/4.9/cluster-kube-descheduler-operator.v4.9.0.clusterserviceversion.yaml
manifests/4.9/kube-descheduler-operator.crd.yaml
pkg/apis/descheduler/v1/types_descheduler.go
pkg/operator/target_config_reconciler.go
pkg/operator/target_config_reconciler_test.go

In https://github.com/openshift/cluster-kube-descheduler-operator/pull/168 we added default behavior to the operator to ignore pods with PVCs (the upstream default is to evict pods with PVCs, but we had a specific bug to ignore them).
Therefore, adding a profile to ignore pods with PVCs was redundant and unclear in context of the existing default behavior of the operator. Before we release `DoNotEvictPodsWithPVC` in 4.9, this changes it to `EvictPodsWithPVC` which allows PVC pods to be evicted.

Bug 1997787: Rename DoNotEvictPodsWithPVC->EvictPodsWithPVC

---

manifests/4.6/cluster-kube-descheduler-operator.v4.6.0.clusterserviceversion.yaml
manifests/art.yaml

`olm.skipRange` substitution as defined in `manifests/art.yml` has been a noop. This fixes it.

Bug 1995951: Fix olm.skipRange substitution

---

README.md

to help with confusion between `EvictPodsWithPVC` and `EvictPodsWithLocalStorage`

Clarify definition of local storage

---

manifests/4.8/cluster-kube-descheduler-operator.v4.8.0.clusterserviceversion.yaml

```
E0915 02:52:11.420001       1 target_config_reconciler.go:425] key failed with : storageversionmigrations.migration.k8s.io "operator-kubedescheduler-storage-version-migration" is forbidden: User "system:serviceaccount:openshift-kube-descheduler-operator:openshift-descheduler" cannot get resource "storageversionmigrations" in API group "migration.k8s.io" at the cluster scope
```

bug 1991938: Add missing RBAC for storageversionmigrations.migration.k8s.io

---

pkg/operator/target_config_reconciler.go

Follow up a logical error in https://github.com/openshift/cluster-kube-descheduler-operator/pull/215 that caused this check to fail with `key failed with : storageversionmigrations.migration.k8s.io "operator-kubedescheduler-storage-version-migration" not found` (due to the fact that `Get()` returns a non-nil object when returning an error)

[release-4.8] Bug 1991938: Fix logic check in migration for 4.8

---

manifests/4.8/cluster-kube-descheduler-operator.v4.8.0.clusterserviceversion.yaml

Currently 4.8 is reporting this error:
```
E1102 12:07:33.814476       1 target_config_reconciler.go:425] key failed with : customresourcedefinitions.apiextensions.k8s.io "kubedeschedulers.operator.openshift.io" is forbidden: User "system:serviceaccount:openshift-kube-descheduler-operator:openshift-descheduler" cannot get resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```
Add this permission to the CSV so that it can properly perform the v1beta1->v1 migration

[release-4.8] Bug 1991938: Add permissions to get CRDs in config migration

---

deploy/0000_00_kube-descheduler-operator.crd.yaml
deploy/02_clusterrole.yaml
manifests/4.10/cluster-kube-descheduler-operator.v4.10.0.clusterserviceversion.yaml
pkg/operator/configobservation/configobservercontroller/observe_config_controller.go
pkg/operator/configobservation/interfaces.go
pkg/operator/resourcesynccontroller/resourcesynccontroller.go
pkg/operator/starter.go
pkg/operator/target_config_reconciler.go
vendor/github.com/openshift/library-go/pkg/operator/condition/condition.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/OWNERS
vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/listers.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_audit.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_cors.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/apiserver/observe_tlssecurityprofile.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/config_observer_controller.go
vendor/github.com/openshift/library-go/pkg/operator/configobserver/unstructured.go
vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/core.go
vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/interfaces.go
vendor/github.com/openshift/library-go/pkg/operator/resourcesynccontroller/resourcesync_controller.go
vendor/modules.txt

To support cluster wide cryptographic policy as is done in KS, KA and KCM.
Originally reported in https://bugzilla.redhat.com/show_bug.cgi?id=1844989 and resolved as part of https://issues.redhat.com/browse/WRKLDS-241 for KS, KA and KCM
Following the same code changes as performed in https://github.com/openshift/cluster-kube-controller-manager-operator/pull/506.

bug 2041581: Allow to set ciphers through observed config

---

Dockerfile.rhel7

`go build` does not take into account env variables populated by the building system. `make build` does by populating GO_LD_FLAGS env (see https://github.com/openshift/cluster-kube-descheduler-operator/blob/master/vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk).

bug 2041466: Dockerfile: use make build instead of go build

---

manifests/4.10/cluster-kube-descheduler-operator.v4.10.0.clusterserviceversion.yaml

The operator kubernetes dependencies bumped in https://github.com/openshift/cluster-kube-descheduler-operator/pull/233.

bug 2041326: Update the minKubeVersion in the CSV to reflect the v1.23 rebase

---

Dockerfile
Dockerfile.rhel7

go build does not take into account env variables populated by the
building system.
make build does by populating GO_LD_FLAGS env (see
https://github.com/openshift/cluster-kube-descheduler-operator/blob/master/vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk).

bug 2042849: Dockerfile: use make build instead of go build

---

Dockerfile.metadata
README.md
manifests/4.10/kube-descheduler-operator.crd.yaml
pkg/apis/descheduler/v1/types_descheduler.go
pkg/operator/target_config_reconciler.go
pkg/operator/target_config_reconciler_test.go

Supersedes https://github.com/openshift/cluster-kube-descheduler-operator/pull/218
- add hypershift to list of default excluded namespaces (https://bugzilla.redhat.com/show_bug.cgi?id=2000653)
- customize threshold priority params strategies wide (https://issues.redhat.com/browse/WRKLDS-303)

Bug 2000653: Customize threshold priority params strategies wide, exclude hyperkube namespace

---

deploy/02_clusterrole.yaml
manifests/4.8/cluster-kube-descheduler-operator.v4.8.0.clusterserviceversion.yaml

Add missing RBAC rule for updating kubedeschedulers.operator.openshift.io CRD status
```
E0316 15:26:00.119302       1 target_config_reconciler.go:425] key failed with : customresourcedefinitions.apiextensions.k8s.io "kubedeschedulers.operator.openshift.io" is forbidden: User "system:serviceaccount:openshift-kube-descheduler-operator:openshift-descheduler" cannot update resource "customresourcedefinitions/status" in API group "apiextensions.k8s.io" at the cluster scope
```

bug 1991938: Add missing rbac

---

deploy/0000_00_kube-descheduler-operator.crd.yaml

This was missed in #245
/assign @ingvagabund

Fix kube-descheduler operator CRD link

---

bindata/assets/kube-descheduler/operandserviceaccount.yaml

```
E0407 09:07:47.029627       1 runtime.go:78] Observed a panic: &fs.PathError{Op:"open", Path:"assets/kube-descheduler/operandserviceaccount.yaml", Err:(*errors.errorString)(0xc00007c040)} (open assets/kube-descheduler/operandserviceaccount.yaml: file does not exist)
goroutine 345 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x20a47c0, 0xc0008b7410})
k8s.io/[apimachinery@v0.23.0](mailto:apimachinery@v0.23.0)/pkg/util/runtime/runtime.go:74 +0x7d
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x26bba90})
k8s.io/[apimachinery@v0.23.0](mailto:apimachinery@v0.23.0)/pkg/util/runtime/runtime.go:48 +0x75
panic({0x20a47c0, 0xc0008b7410})
runtime/panic.go:1038 +0x215
github.com/openshift/cluster-kube-descheduler-operator/bindata.MustAsset(...) …
```

bug 2072911: Provide missing SA file

---

manifests/4.11/cluster-kube-descheduler-operator.v4.11.0.clusterserviceversion.yaml

Mirroring https://github.com/openshift/cluster-kube-scheduler-operator/pull/421
Follow up for https://github.com/openshift/cluster-kube-descheduler-operator/pull/257. Applying the change in the operator deployment as well.

bug 2079805: [operator] manifests/deployment: comply to restricted pod security level

---

manifests/4.11/cluster-kube-descheduler-operator.v4.11.0.clusterserviceversion.yaml

Reference BZ 2093783. Bumping minKubeVersion on manifests/4.11/cluster-kube-descheduler-operator.v4.11.0.clusterserviceversion.yaml
Is anything else needed here? :)

bug 2093783: bump minKubeVersion to 1.24

---

pkg/operator/target_config_reconciler.go
vendor/github.com/openshift/library-go/pkg/controller/ownerref.go
vendor/modules.txt

The BZ is for an older version of Openshift, I am still not familiar with backporting stuff, so I will need help there.
~Also, I got a bunch of changes coming from go mod vendor and go mod tidy, not sure those should come here.~ (seems to be ok now)

bug 1957012: set ownerReference correctly

---

manifests/4.12/cluster-kube-descheduler-operator.v4.12.0.clusterserviceversion.yaml

Adds arm64 support to operator hub.
ARM QE validated descheduler for arm64 
cc: @aleskandro @andymcc

Enable descheduler for arm64

---

bindata/assets/kube-descheduler/operandclusterrole.yaml

descheduler is using the new events api, and we need to update rbac to align with it

OCPBUGS-2330: add new events apiGroup

---

bindata/assets/kube-descheduler/deployment.yaml

The binary asset deployment.yaml specifys the `--v=2` to set the logging level. 
In the Operator's pod, I noticed this:
```
spec:
containers:
- args:
- --policy-config-file=/policy-dir/policy.yaml
- --v=2
- --logging-format=text
- --tls-cert-file=/certs-dir/tls.crt
- --tls-private-key-file=/certs-dir/tls.key
- --descheduling-interval=60s
- --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
- --tls-min-version=VersionTLS12
- -v=8
```
This is due to [source](https://github.com/openshift/cluster-kube-descheduler-operator/blob/master/pkg/operator/target_config_reconciler.go#L608) …

Duplicate logging level specified in the generated Pod

---

pkg/operator/target_config_reconciler.go
pkg/operator/target_config_reconciler_test.go

This is possible starting on 4.13, https://github.com/kubernetes-sigs/descheduler/tree/93a014ef5ebe66d4945f5ad181deb5af9c61ccd8#namespace-filtering + https://github.com/kubernetes-sigs/descheduler/issues/1005 + https://issues.redhat.com/browse/OCPBUGS-513

Allow ns exclusion, error on inclusion for nodeutilization

---

manifests/art.yaml
manifests/cluster-kube-descheduler-operator.package.yaml
manifests/stable/cluster-kube-descheduler-operator.v4.13.0.clusterserviceversion.yaml
manifests/stable/image-references
test/e2e/operator_test.go

Reverts openshift/cluster-kube-descheduler-operator#285
Temporarily reverting before the branching so release-4.13 is aligned with 4.13 version.

OCPBUGS-7876: Revert "manifests to 4.14"

---

bindata/assets/kube-descheduler/deployment.yaml

With measurements provided from one of our descheduler contributors the memory consumption of the descheduler in a big cluster can grow over 1.5GB. The same observation holds for the kube-scheduler which has no resource limits defined. Comparing graphs of memory consuption of both the descheduler and the kube-scheduler shows a very similar pattern.

OCPBUGS-1995: Drop descheduler operand resource limits

---

manifests/cluster-kube-descheduler-operator.package.yaml

With 4.14, ART no longer forces a stable channel, but instead uses what you have here as the channel list. You probably want it to be `stable`.
reference [slack chat](https://redhat-internal.slack.com/archives/CB95J6R4N/p1694127434005319?thread_ts=1694094694.738739&cid=CB95J6R4N) and you'll want to backport this to 4.14 as well.

use `stable` channel in CSV

---

pkg/operator/target_config_reconciler.go

While we met error from the configmap and force a deployment scale to 0, the name of descheduler deployment is wrong.
error log by `target_config_reconciler.go` is
```
key failed with : deployments.apps "cluster" not found
```

fix: descheduler deployment wrong name

---

Dockerfile.metadata
Dockerfile.rhel7
deploy/05_deployment.yaml
manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
test/e2e/bindata/assets/05_deployment.yaml

readOnlyRootFilesystem SecurityContext is enabled by default in Deployment object definition. As a result, /tmp is read-only and not writable.

Operator deployment: set an emptyDir /tmp

---

Dockerfile.rhel7
deploy/0000_00_kube-descheduler-operator.crd.yaml
deploy/05_deployment.yaml
manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
test/e2e/bindata/assets/05_deployment.yaml

readOnlyRootFilesystem SecurityContext is enabled by default in Deployment object definition. As a result, /tmp is read-only and not writable.

NO-JIRA: Operator deployment: set an emptyDir /tmp

---

manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml

The first time we use a buffer for skipped releases to maintain a reachable to-be-added-patch-releases in the future so `opm index add` is happy to accept the patch releases for all existing index bundle images.

WRKLDS-1239: Prepare 5.1.0 release

---

manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml

```
E0904 12:58:23.891848       1 target_config_reconciler.go:1044] key failed with : clusterroles.rbac.authorization.k8s.io "openshift-descheduler-operand" is forbidden: user "system:serviceaccount:openshift-kube-descheduler-operator:openshift-descheduler" (groups=["system:serviceaccounts" "system:serviceaccounts:openshift-kube-descheduler-operator" "system:authenticated"]) is attempting to grant RBAC permissions not currently held:
{APIGroups:[""], Resources:["nodes"], Verbs:["get" "watch" "list"]}
{APIGroups:[""], Resources:["pods/eviction"], Verbs:["create"]}
{APIGroups:["scheduling.k8s.io"], Resources:["priorityclasses"], Verbs:["get" "watch" "list"]}
I0904 12:58:23.891932       1 event.go:377] Event(v1.ObjectReference{Kind:"Deployment", …
```

Operator clusterrole needs rbac operand grants

---

deploy/02_clusterrole.yaml
hack/manifest2clusterrole.sh
test/e2e/bindata/assets/03_clusterrole.yaml
test/e2e/bindata/assets/04_clusterrolebinding.yaml

To keep the manifest based clusterrole in sync with deploy used for quick development testing.

no-jira: Manifest2clusterrole

---

manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml

Backporting https://github.com/openshift/cluster-kube-descheduler-operator/pull/376 to 5.0.z

OCPBUGS-41994: Operator clusterrole needs rbac operand grants

---

manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml

Add a few annotations:
- operatorframework.io/cluster-monitoring: "true"
- operatorframework.io/suggested-namespace: "openshift-kube-descheduler-operator"
- console.openshift.io/operator-monitoring-default: "true" to simplify the deployment via OCP console.

no-jira: Set suggested-namespace and related annotations

---

README.md
pkg/apis/descheduler/v1/types_descheduler.go
pkg/operator/target_config_reconciler.go

CPU PSI pressure as measured by the Kernel is not able to discriminate self imposed pressure due to CPU throttling on CPU limited containers from pressure caused by resource contention with other neighbors.
See: https://github.com/kubernetes/enhancements/issues/5062
In order to filter out evident false positives, we can introduce a new ActualUtilizationProfile that is consuming CPU PSI pressure value only when the actual average CPU utilization on the node is above a certain threshold (70%), otherwise 0.
This is not a systematic solution but a mitigation.
Fixes: https://issues.redhat.com/browse/OCPBUGS-52341

OCPBUGS-52341: Add CPUPSIPressureUtilization ActualUtilizationProfile

---

.tekton/images-mirror-set.yaml
.tekton/kube-descheduler-operator-fbc-4-18-pull-request.yaml
.tekton/kube-descheduler-operator-fbc-4-18-push.yaml

All products building FBC fragments in Konflux are requested to merge this change irrespective of whether the product is intended for FIPS mode or not.
Beginning March 1, 2025, the fbc-fips-task is going to be a required task in the Konflux
pipeline. This means, your release will be blocked if this task is not present in your pipeline run.
The answer is yes. If your product is not designed to operate in FIPS mode, the task will identify that and will
automatically skip the FIPS scan. However, the task still needs to be a part of your pipeline.
* This commit adds the fbc-fips-check task to your pipeline yaml.
* It also adds a file named `images-mirror-set.yaml` to your `.tekton` directory with an example in it. This file is an `ImageDigestMirrorSet` required by the task to access any …

RELEASE BLOCKER(March 1, 2025): add fbc-fips-check task to FBC pipeline

---

pkg/operator/target_config_reconciler.go
pkg/operator/target_config_reconciler_test.go
pkg/operator/testdata/assets/lowNodeUtilizationIncludedNamespace.yaml

LowNodeUtilization does not support namespace inclusion. Thus, the list of excluded namespace needs to fall back to the list of protected namespace instead of not setting ommiting the namespace inclusion.

OCPBUGS-54414: Lownodeutilization fall back to protected namespaces when ns inclusion

---

README.md
pkg/operator/target_config_reconciler.go
pkg/operator/testdata/assets/relieveAndMigrateHighConfig.yaml
pkg/operator/testdata/assets/relieveAndMigrateIncludedNamespace.yaml
pkg/operator/testdata/assets/relieveAndMigrateLowConfig.yaml
pkg/operator/testdata/assets/relieveAndMigrateMediumConfig.yaml

Both profiles (eviction of pods with a PVC and a local storage) are a common kubevirt use cases.

CNTRLPLANE-260: devKubeVirtRelieveAndMigrate: enable EvictPodsWithPVC and EvictPodsWithLocalStorage by default

---

pkg/operator/target_config_reconciler.go
pkg/operator/target_config_reconciler_test.go

Return an explict error when DevKubeVirtRelieveAndMigrate is configured but KubeVirt is not deployed.

Explicit error for DevKubeVirtRelieveAndMigrate without KubeVirt

---

bindata/assets/kube-descheduler/softtaintervalidatingadmissionpolicy.yaml
pkg/operator/target_config_reconciler.go
pkg/operator/target_config_reconciler_test.go
pkg/softtainter/softtainter.go
test/e2e/bindata/assets/00_kube-descheduler-operator-crd.yaml
test/e2e/bindata/assets/07_descheduler-operator.cr.devKubeVirtRelieveAndMigrate.yaml
test/e2e/operator_test.go

Backporting https://github.com/openshift/cluster-kube-descheduler-operator/pull/496, https://github.com/openshift/cluster-kube-descheduler-operator/pull/495 and https://github.com/openshift/cluster-kube-descheduler-operator/pull/494 to 4.18.

no-jira: TargetConfigReconciler: extend TestSync with a condition check for DevKubeVirtRelieveAndMigrate operator profile

---

README.md
manifests/kube-descheduler-operator.crd.yaml
pkg/apis/descheduler/v1/types_descheduler.go
pkg/operator/target_config_reconciler.go
pkg/operator/target_config_reconciler_test.go
pkg/softtainter/softtainter.go
pkg/softtainter/softtainter_test.go
pkg/softtainter/testdata/policyNoRelieveAndMigrate.yaml
test/e2e/bindata/assets/00_kube-descheduler-operator-crd.yaml
test/e2e/bindata/assets/07_descheduler-operator.cr.devKubeVirtRelieveAndMigrate.yaml

The SoftTainter is a critical mandatory
component for the correct behaviour of the
KubeVirtRelieveAndMigrate profile.
Have it always deployed when KubeVirtRelieveAndMigrate
is in use.
Deprecate DevEnableSoftTainter.
Fixes: https://issues.redhat.com/browse/WRKLDS-1673

Have the SoftTainter always deployed with KubeVirtRelieveAndMigrate

---

README.md
bindata/assets/kube-descheduler/psialert.yaml
pkg/operator/target_config_reconciler.go
pkg/operator/target_config_reconciler_test.go
test/e2e/operator_test.go

RelieveAndMigrate profile requires PSI metric to be enabled for the worker nodes (psi=1 kernel parameter). Directly check it for the node that is executing the operator pod, looking if /proc/pressure/ is available inside the pod, and report it with a condition.
Check it for all the worker nodes and report it also with an alert.
Fixes: https://issues.redhat.com/browse/WRKLDS-1673

Add an alert and an condition for RelieveAndMigrate without PSI

---

pkg/operator/target_config_reconciler.go
pkg/operator/target_config_reconciler_test.go
pkg/softtainter/softtainter.go
pkg/softtainter/softtainter_test.go

as we fail when the scheduling interval isn't set we should also fail when it is set to an invalid value.

OCPBUGS-57338: error out on zeroed scheduling interval

---

bundle.Dockerfile

The tekton fbc jobs already defines registry mirroring. So no need to provide staging prefix for pre-release testing.

bundle.Dockerfile: registry.stage.redhat.io -> registry.redhat.io

---

.tekton/kube-descheduler-operator-4-19-pull-request.yaml
.tekton/kube-descheduler-operator-4-19-push.yaml
.tekton/kube-descheduler-operator-bundle-4-19-pull-request.yaml
.tekton/kube-descheduler-operator-bundle-4-19-push.yaml

Blocking https://github.com/openshift/cluster-kube-descheduler-operator/pull/537

no-jira: .tekton: new task updates require IMAGE_URL and IMAGE_DIGEST envs to be present for apply-tags task
