openshift/cluster-kube-descheduler-operator

hack/install.sh
Fix path to work with olm based csv
=> Update install.sh to work with olm based csv

pkg/stub/handler.go
/cc @sjenning 
Fixing the binary path
=> Fix descheduler binary path

OWNERS, README.md, deploy/operator.yaml
Update readme and operator deployment.yaml
=> Fix README and create a operator.yaml

pkg/apis/descheduler/v1alpha1/descheduler_types.go, pkg/controller/descheduler/descheduler_controller.go, pkg/controller/descheduler/descheduler_controller_test.go
Add some basic validation for strategies. As of now, based on string validation that is shoved into configmap.
/cc @sjenning
=> Add basic validation for strategies

Makefile, hack/verify-gofmt.sh
A sample make file for running tests.
/cc @sjenning
=> Make file 

README.md
Update readme with latest CR changes.
/cc @sjenning
=> Update readme with latest CR changes

deploy/rbac.yaml, deploy/role.yaml
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1656760
Tested this. Forgot to push rbac, when I pushed changes last time.
=> Add cron job resources

README.md, pkg/controller/descheduler/descheduler_controller.go, pkg/controller/descheduler/descheduler_controller_test.go
- Add no of nodes param
- Update readme
Fixes: #32 
/cc @sjenning
=> Add number of node param for lownodeutilization strategy

pkg/controller/descheduler/descheduler_controller.go, test/e2e/descheduler_test.go
Update descheduler CR to ensure updates are happening immediately.
=> Update descheduler cr immediately

pkg/controller/descheduler/descheduler_controller.go
Add logging for descheduler container so as to avoid regression with 3.11
=> Add logs for descheduler

pkg/controller/descheduler/descheduler_controller.go
=> Refactor for updating status

manifests/4.4/image-references
=> Reference descheduler image in image-references

Dockerfile, README.md, manifests/4.4/cluster-kube-descheduler-operator.v4.4.0.clusterserviceversion.yaml
/hold
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1812629
=> Update operator description in CSV

manifests/4.5/cluster-kube-descheduler-operator.v4.5.0.clusterserviceversion.yaml
=> bug 1842853: csv: set minKubeVersion to 1.18 to reflect vendored k8s libraries

Dockerfile, Dockerfile.rhel7
=> Bug 1855575: Bump to go 1.14

manifests/4.6/cluster-kube-descheduler-operator.v4.6.0.clusterserviceversion.yaml
=> bug 1879522: 4.6 manifests: bump minKubeVersion to 1.19.0

README.md, manifests/4.7/cluster-kube-descheduler-operator.v4.6.0.clusterserviceversion.yaml, manifests/4.7/cluster-kube-descheduler-operator.v4.7.0.clusterserviceversion.yaml, manifests/4.7/image-references, manifests/4.7/kube-descheduler-operator.crd.yaml, manifests/cluster-kube-descheduler-operator.package.yaml
```
Error Reported
--------------
ose-cluster-kube-descheduler-operator: file does not exist: /mnt/workspace/jenkins/working/.../containers/ose-cluster-kube-descheduler-operator/manifests/4.7/image-references
```
=> Manifests 4.7

pkg/operator/starter.go, pkg/operator/target_config_reconciler.go, vendor/github.com/openshift/library-go/pkg/operator/loglevel/logging_controller.go, vendor/github.com/openshift/library-go/pkg/operator/loglevel/util.go, vendor/modules.txt
fixes https://github.com/openshift/cluster-kube-descheduler-operator/issues/150
=> Parse LogLevel operator spec setting

bindata/v4.1.0/kube-descheduler/deployment.yaml, deploy/05_deployment.yaml, manifests/4.7/cluster-kube-descheduler-operator.v4.7.0.clusterserviceversion.yaml, pkg/operator/starter.go, pkg/operator/target_config_reconciler.go, pkg/operator/v410_00_assets/bindata.go
Fixes https://github.com/openshift/cluster-kube-descheduler-operator/issues/158
=> Add support for IMAGE env var

manifests/4.7/cluster-kube-descheduler-operator.v4.7.0.clusterserviceversion.yaml
4.7 descheduler operator deploys 1.20 descheduler
=> bug 1910305: csv: set minKubeVersion to 1.20.0

bindata/v4.1.0/kube-descheduler/deployment.yaml, bindata/v4.1.0/kube-descheduler/role.yaml, bindata/v4.1.0/kube-descheduler/rolebinding.yaml, bindata/v4.1.0/kube-descheduler/service.yaml, bindata/v4.1.0/kube-descheduler/servicemonitor.yaml, deploy/01_namespace.yaml, pkg/operator/starter.go, pkg/operator/target_config_reconciler.go, pkg/operator/v410_00_assets/bindata.go
Builds in top of https://github.com/kubernetes-sigs/descheduler/pull/505
=> Publish descheduler metrics

manifests/4.8/cluster-kube-descheduler-operator.v4.8.0.clusterserviceversion.yaml
=> bug 1941980: Add rbac rules for rendering metric related manifests

README.md
=> LifecycleAndUtilization profile: mention RemovePodsHavingTooManyRestarts is included as well

manifests/4.8/cluster-kube-descheduler-operator.v4.8.0.clusterserviceversion.yaml
https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#resources-and-limits
=> bug 1947771: descheduler operator: set resource requests

manifests/4.6/cluster-kube-descheduler-operator.v4.6.0.clusterserviceversion.yaml, manifests/4.7/cluster-kube-descheduler-operator.v4.7.0.clusterserviceversion.yaml
Following https://github.com/openshift/cluster-kube-descheduler-operator/pull/181
=> bug 1947771: descheduler operator: set resource requests [4.6, 4.7]

manifests/4.4/cluster-kube-descheduler-operator.v4.4.0.clusterserviceversion.yaml, manifests/4.5/cluster-kube-descheduler-operator.v4.5.0.clusterserviceversion.yaml, manifests/4.6/cluster-kube-descheduler-operator.v4.6.0.clusterserviceversion.yaml, manifests/4.7/cluster-kube-descheduler-operator.v4.7.0.clusterserviceversion.yaml
https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#resources-and-limits
=> bug 1948267: descheduler operator: set resource requests

manifests/4.8/cluster-kube-descheduler-operator.v4.8.0.clusterserviceversion.yaml
=> bug 1950232: manifests 4.8: set minKubeVersion to 1.21

manifests/4.8/cluster-kube-descheduler-operator.v4.8.0.clusterserviceversion.yaml
olm.skipRange string has to match with a search pattern in art.yaml to
have it properly replaced with the right version
=> bug 1943224: Have olm.skipRange in csv correspond to search pattern in art.yaml

manifests/4.7/cluster-kube-descheduler-operator.v4.7.0.clusterserviceversion.yaml, manifests/art.yaml
olm.skipRange string has to match with a search pattern in art.yaml to
have it properly replaced with the right version
=> bug 1953707: Have olm.skipRange in csv correspond to search pattern in art.yaml

manifests/4.8/kube-descheduler-operator.crd.yaml
=> bug 1955595: Remove CRD top dashes

.ci-operator.yaml, Dockerfile.rhel7, manifests/4.9/cluster-kube-descheduler-operator.v4.9.0.clusterserviceversion.yaml, manifests/4.9/image-references, manifests/4.9/kube-descheduler-operator.crd.yaml, manifests/cluster-kube-descheduler-operator.package.yaml
Part of [ART-2868](https://issues.redhat.com/browse/ART-2868), update CSV channels to be able to re-enable automated builds for this image.
=> release-4.9-olm-manifests

bindata/assets/profiles/SoftTopologyAndDuplicates.yaml, manifests/4.9/kube-descheduler-operator.crd.yaml, pkg/apis/descheduler/v1/types_descheduler.go, pkg/operator/target_config_reconciler.go
Adds a copy of the `TopologyAndDuplicates` profile which includes soft constraints
Ref https://issues.redhat.com/browse/WRKLDS-302
=> Bug 1989722: Add SoftTopologyAndDuplicates profile

README.md
Follow up https://github.com/openshift/cluster-kube-descheduler-operator/pull/201 to update readme describing profileCustomizations (and example in sample CR)
=> Bug 1989720: Add profile customizations to README

bindata/assets/kube-descheduler/deployment.yaml
Adds new `default-containter` annotation to deployment.
/assign @soltysh
=> Bug 2035986: Add default-container annotation

OWNERS
=> bug 2043240: Remove damemi from OWNERS

bindata/assets/kube-descheduler/service.yaml
service-ca-operator uses newer annotations @soltysh
=> update cert injection annotation to beta

manifests/4.11/cluster-kube-descheduler-operator.v4.11.0.clusterserviceversion.yaml
=> CSV: add subscription

manifests/cluster-kube-descheduler-operator.package.yaml
To be aligned with the CSV in 4.11 branch
=> Set the channel name to 4.11

pkg/operator/operatorclient/interfaces.go, pkg/operator/starter.go, pkg/operator/target_config_reconciler.go
=> Use descheduler name for the deployment

Makefile, README.md, manifests/4.11/kube-descheduler-operator.crd.yaml, pkg/apis/descheduler/v1/types_descheduler.go, pkg/apis/descheduler/v1/zz_generated.deepcopy.go, pkg/generated/clientset/versioned/clientset.go, pkg/generated/clientset/versioned/typed/descheduler/v1/descheduler_client.go, pkg/generated/clientset/versioned/typed/descheduler/v1/fake/fake_kubedescheduler.go, pkg/operator/target_config_reconciler.go
=> Descheduler modes

Dockerfile.rhel7, bindata/assets/kube-descheduler/deployment.yaml, manifests/4.11/cluster-kube-descheduler-operator.v4.11.0.clusterserviceversion.yaml
Mirroring https://github.com/openshift/cluster-kube-scheduler-operator/pull/421
To resolve https://issues.redhat.com/browse/AUTH-222
=> bug 2079805: manifests/deployment: comply to restricted pod security level

README.md
Went through this process a bunch of times today, just noticed some small improvements that could help.
=> bug 1957012: docs: few tweaks to readme

pkg/operator/target_config_reconciler.go
Use ApplyDeployment instead of ApplyDeploymentWithForce 
since in ApplyDeployment it sets an anotation that is the hash of the spec: https://github.com/openshift/library-go/blob/245d1ca16d1514313f3a7ab13ff2c9e3b07b5f43/pkg/operator/resource/resourceapply/apps.go#L95
and ApplyDeployment calls ApplyDeploymentWithForce, which then checks that hash to decide or not to force apply: https://github.com/openshift/library-go/blob/master/pkg/operator/resource/resourceapply/apps.go#L131
=> Use ApplyDeployment instead of ApplyDeploymentWithForce

.ci-operator.yaml, Dockerfile.rhel7, go.mod, pkg/generated/clientset/versioned/fake/register.go, pkg/generated/clientset/versioned/scheme/register.go
Needed by https://github.com/openshift/cluster-kube-descheduler-operator/pull/275
=> Bump go.mod golang version to 1.19

Dockerfile.rhel7, manifests/art.yaml, manifests/cluster-kube-descheduler-operator.package.yaml, manifests/stable/cluster-kube-descheduler-operator.v4.14.0.clusterserviceversion.yaml, manifests/stable/image-references, test/e2e/operator_test.go
Updated to 4.14 everywhere, except for operands version. Please let me know if I should also bump the operand
=> manifests to 4.14

manifests/stable/cluster-kube-descheduler-operator.v4.14.0.clusterserviceversion.yaml
=> CSV: set minKubeVersion

manifests/stable/cluster-kube-descheduler-operator.v4.13.0.clusterserviceversion.yaml
=> OCPBUGS-7147: CSV: bump min k8s version to 1.26.0

manifests/stable/cluster-kube-descheduler-operator.v4.14.0.clusterserviceversion.yaml, test/e2e/operator_test.go
=> OCPBUGS-13579: Bump minKubeVersion to 1.27

manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml, manifests/kube-descheduler-operator.crd.yaml
For https://issues.redhat.com/browse/WRKLDS-905
=> WRKLDS-905: cpaas: prepare 5.0.0 release

hack/install-from-brew.sh
=> NO-JIRA: hack: script to install the latest bundle from Brew

pkg/operator/starter.go, test/e2e/bindata/assets/05_deployment.yaml, test/e2e/operator_test.go
=> OCPBUGS-24597: Operand image is injected through RELATED_IMAGE_OPERAND_IMAGE

Makefile
=> OCPBUGS-25992: Makefile: add strictfipsruntime build tag

README.md
=> NO-JIRA: Readme: KDO releases

.snyk
=> OCPBUGS-23586: Add .snyk file to exclude vendor and ignore unit tests

.snyk, Makefile, README.md, hack/install-from-brew.sh, pkg/operator/starter.go, test/e2e/bindata/assets/05_deployment.yaml, test/e2e/operator_test.go
=> NO-JIRA: Sync with master

README.md
=> NO-JIRA: no-op to trigger cpass build

manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
=> NO-JIRA: CSV: set spec.replaces

manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
=> NO-JIRA: csv: update spec.replaces to a released version

manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
=> NO-JIRA: CSV: update replace and subs type

OWNERS
=> NO-JIRA: OWNERS: fix component name

manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
=> no-jira: csv: Set required Infrastructure Annotations

manifests/stable/cluster-kube-descheduler-operator.v4.14.0.clusterserviceversion.yaml
=> OCPBUGS-30616: [4.14] csv: set required infrastructure annotations

manifests/stable/cluster-kube-descheduler-operator.v4.13.0.clusterserviceversion.yaml
=> OCPBUGS-30617: [4.13] csv: set required infrastructure annotations

manifests/4.12/cluster-kube-descheduler-operator.v4.12.0.clusterserviceversion.yaml
=> OCPBUGS-30618: [4.12] csv: set required infrastructure annotations

bindata/assets/kube-descheduler/deployment.yaml, deploy/05_deployment.yaml, manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
operand: https://issues.redhat.com/browse/WRKLDS-1146
operator: https://issues.redhat.com/browse/WRKLDS-1147
=> WRKLDS-1146: Set readOnlyRootFilesystem to true

Dockerfile.metadata
=> wrong changes

manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
=> CSV: claim features.operators.openshift.io/disconnected as true

manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
=> CSV: update replaced field to point to an existing version

Makefile, bindata/assets/profiles/LongLifecycle.yaml, manifests/kube-descheduler-operator.crd.yaml, pkg/apis/descheduler/v1/types_descheduler.go, pkg/operator/target_config_reconciler.go
Deprecate DevPreviewLongLifecycle in 4.17
=> WRKLDS-1302: Promote DevPreviewLongLifecycle to LongLifecycle

Dockerfile.metadata, Dockerfile.rhel7, README.md, manifests/kube-descheduler-operator.crd.yaml
=> Update Dockerfiles and the testing instructions

bindata/assets/kube-descheduler/deployment.yaml, deploy/05_deployment.yaml, manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
=> operand: fix containers[].securityContext.readOnlyRootFilesystem field name

bindata/assets/kube-descheduler/operandclusterrole.yaml, deploy/02_clusterrole.yaml, manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml, test/e2e/bindata/assets/03_clusterrole.yaml
[OCPBUGS-35569](https://issues.redhat.com/browse/OCPBUGS-35569)
=> OCPBUGS-35569: Replace wildcards by explicit list of verbs

README.md
=> README: update releases table

README.md, deploy/02_clusterrole.yaml, deploy/05_deployment.yaml, manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
=> no-jira: Update rbac and deploy manifests for local testing

manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
=> WRKLDS-1239: csv: add missing v letter in the operator name versions

manifests/kube-descheduler-operator.crd.yaml, test/e2e/bindata/assets/00_kube-descheduler-operator-crd.yaml
=> no-jira: Regen crd

pkg/operator/target_config_reconciler.go, pkg/operator/target_config_reconciler_test.go
=> WRKLDS-1428: Scale down descheduler deployment to zero when there's a profile configuration conflict

manifests/kube-descheduler-operator.crd.yaml, pkg/apis/descheduler/v1/types_descheduler.go, pkg/operator/target_config_reconciler.go, pkg/operator/target_config_reconciler_test.go, test/e2e/bindata/assets/00_kube-descheduler-operator-crd.yaml
Resolves: https://github.com/openshift/cluster-kube-descheduler-operator/issues/378
=> no-jira: [customization] UtilizationThresholds: allow an empty threshold

manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
=> WRKLDS-1239: csv: replace 5.0.1 as 5.0.0 no longer exists

manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
=> WRKLDS-1561: Prepare 5.0.2 release

README.md
=> no-jira: update releases

README.md
=> no-jira: README: update releases

manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
=> WRKLDS-1586: Prepare csv for 5.1.1 release

README.md
=> no-jira: No op

Dockerfile, bundle.Dockerfile, hack/replace-image.sh
=> WRKLDS-1537: Konflux onboarding

.tekton/kube-descheduler-operator-4-18-pull-request.yaml, .tekton/kube-descheduler-operator-4-18-push.yaml, .tekton/kube-descheduler-operator-bundle-4-18-pull-request.yaml, .tekton/kube-descheduler-operator-bundle-4-18-push.yaml
=> WRKLDS-1537: [tekton]: build source image, hermetic builds, multiarch

.tekton/kube-descheduler-operator-fbc-4-18-pull-request.yaml, .tekton/kube-descheduler-operator-fbc-4-18-push.yaml
=> [tekton]: Change build pipeline to use multi-arch matrix builds

Dockerfile, bundle.Dockerfile, catalogsource.yaml, hack/replace-image.sh
=> no-jira: [konflux] Dockerfiles for operator and bundle

LICENSE
=> no-jira: Add license

.tekton/kube-descheduler-operator-4-16-pull-request.yaml, .tekton/kube-descheduler-operator-4-16-push.yaml, .tekton/kube-descheduler-operator-bundle-4-16-pull-request.yaml, .tekton/kube-descheduler-operator-bundle-4-16-push.yaml
=> no-jira: [tekton]: build source image, hermetic builds, multiarch

Dockerfile
=> no-jira: Fix Dockerfile base image

.tekton/kube-descheduler-operator-fbc-4-16-pull-request.yaml, .tekton/kube-descheduler-operator-fbc-4-16-push.yaml
=> no-jira: [tekton]: Change build pipeline to use multi-arch matrix builds

bundle.Dockerfile
Pulling https://github.com/openshift/cluster-kube-descheduler-operator/pull/424 and https://github.com/openshift/cluster-kube-descheduler-operator/pull/425
=> no-jira: Bump bundle.Dockerfile images

README.md
=> README: update the releases

.tekton/kube-descheduler-operator-fbc-4-18-pull-request.yaml, .tekton/kube-descheduler-operator-fbc-4-18-push.yaml
=> no-jira: Sync tekton jobs to pick up the latest improvements

README.md
=> no-jira: no-op: to re-trigger build pipeline

README.md
=> no-op: to re-trigger build pipeline

README.md
Reverts openshift/cluster-kube-descheduler-operator#478
=> no-jira: Revert "no-op: to re-trigger build pipeline"

bundle.Dockerfile
=> WRKLDS-1652: bump(bundle.Dockerfile): point to the latest images

.tekton/kube-descheduler-operator-bundle-4-18-pull-request.yaml, .tekton/kube-descheduler-operator-bundle-4-18-push.yaml
=> no-jira: [tekton]: update bundle jobs

README.md
=> no-jira: no-op: re-trigger pipeline

.tekton/kube-descheduler-operator-4-18-pull-request.yaml, .tekton/kube-descheduler-operator-4-18-push.yaml
=> no-jira: [tekton]: make the operator configs more up2date

bundle.Dockerfile
=> no-jira: bump(bundle.Dockerfile): point to the latest images

manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
=> WRKLDS-1652: bump(kdo)=5.1.2

.tekton/images-mirror-set.yaml, README.md, v4.18/catalog-template.json, v4.18/catalog/cluster-kube-descheduler-operator/catalog.json
=> WRKLDS-1652: Extend fbc catalog with 5.1.1 and 5.1.2 releases and regen

pkg/operator/target_config_reconciler_test.go
Adding a new test for https://github.com/openshift/cluster-kube-descheduler-operator/pull/494.
=> TargetConfigReconciler: extend TestSync with a condition check for DevKubeVirtRelieveAndMigrate operator profile

bindata/assets/kube-descheduler/softtaintervalidatingadmissionpolicy.yaml, pkg/softtainter/softtainter.go, test/e2e/bindata/assets/00_kube-descheduler-operator-crd.yaml, test/e2e/bindata/assets/07_descheduler-operator.cr.devKubeVirtRelieveAndMigrate.yaml, test/e2e/operator_test.go
Cover also softtainter deployment, its cleanup and its ValidatingAdmissionPolicy in e2e tests.
=> [e2e] test softtainter

README.md
=> README: fix the new profile name

bundle.Dockerfile
=> bundle: point to non-staging registry to use a snapshot for both staging and final release

bundle.Dockerfile
=> bundle: point operator image to the latest one

README.md, bundle.Dockerfile, manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
=> WRKLDS-1686: Prepare for 5.2.0 release

.tekton/kube-descheduler-operator-4-19-pull-request.yaml, .tekton/kube-descheduler-operator-4-19-push.yaml
Pulling from https://github.com/openshift/cluster-kube-descheduler-operator/pull/522.
=> bump(.tekton)=4.19

.tekton/kube-descheduler-operator-4-18-pull-request.yaml, .tekton/kube-descheduler-operator-4-18-push.yaml, .tekton/kube-descheduler-operator-bundle-4-18-pull-request.yaml, .tekton/kube-descheduler-operator-bundle-4-18-push.yaml
=> no-jira: Update the latest tekton changes

.tekton/kube-descheduler-operator-4-20-pull-request.yaml, .tekton/kube-descheduler-operator-4-20-push.yaml, .tekton/kube-descheduler-operator-bundle-4-20-pull-request.yaml, .tekton/kube-descheduler-operator-bundle-4-20-push.yaml
=> Bump tekton to 4.20

manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
=> no-jira: csv: increase the 5.1 version pool

README.md, pkg/operator/target_config_reconciler.go, pkg/operator/target_config_reconciler_test.go, pkg/operator/testdata/assets/relieveAndMigrateDefaults.yaml, pkg/operator/testdata/assets/relieveAndMigrateDynamicThresholdsHigh.yaml, pkg/operator/testdata/assets/relieveAndMigrateDynamicThresholdsLow.yaml, pkg/operator/testdata/assets/relieveAndMigrateDynamicThresholdsMedium.yaml, pkg/operator/testdata/assets/relieveAndMigrateHighConfig.yaml, pkg/operator/testdata/assets/relieveAndMigrateIncludedNamespace.yaml, pkg/operator/testdata/assets/relieveAndMigrateLowConfig.yaml, pkg/operator/testdata/assets/relieveAndMigrateMediumConfig.yaml, pkg/softtainter/softtainter.go, pkg/softtainter/softtainter_test.go
- https://github.com/openshift/cluster-kube-descheduler-operator/pull/563
- https://github.com/openshift/cluster-kube-descheduler-operator/pull/570
=> Backporting 4.20/master fixes to 4.19/KDO 5.2.0 release

README.md
=> no-jira: no-op: retrigger pipeline

README.md, manifests/kube-descheduler-operator.crd.yaml, pkg/apis/descheduler/v1/types_descheduler.go, pkg/operator/target_config_reconciler.go, pkg/operator/target_config_reconciler_test.go, pkg/operator/testdata/assets/relieveAndMigrateDefaults.yaml, pkg/operator/testdata/assets/relieveAndMigrateDeviationLowWithCombinedMetrics.yaml, pkg/operator/testdata/assets/relieveAndMigrateDynamicThresholdsHigh.yaml, pkg/operator/testdata/assets/relieveAndMigrateDynamicThresholdsLow.yaml, pkg/operator/testdata/assets/relieveAndMigrateDynamicThresholdsMedium.yaml, pkg/operator/testdata/assets/relieveAndMigrateEvictionLimits.yaml, pkg/operator/testdata/assets/relieveAndMigrateHighConfig.yaml, pkg/operator/testdata/assets/relieveAndMigrateIncludedNamespace.yaml, pkg/operator/testdata/assets/relieveAndMigrateLowConfig.yaml, pkg/operator/testdata/assets/relieveAndMigrateMediumConfig.yaml, pkg/softtainter/softtainter.go, test/e2e/bindata/assets/00_kube-descheduler-operator-crd.yaml
=> WRKLDS-1728: Promote DevKubeVirtRelieveAndMigrate to GA

deploy/02_clusterrole.yaml
=> Regen deploy/02_clusterrole.yaml

bundle.Dockerfile
=> no-jira: chore(bundle.Dockerfile): pin the operand image to the latest sha

.tekton/kube-descheduler-operator-4-20-pull-request.yaml, .tekton/kube-descheduler-operator-4-20-push.yaml, .tekton/kube-descheduler-operator-bundle-4-20-pull-request.yaml, .tekton/kube-descheduler-operator-bundle-4-20-push.yaml
=> no-jira: fix(.tekton): set rpms-signature-scan task to point to a trusted image

.tekton/kube-descheduler-operator-4-20-pull-request.yaml, .tekton/kube-descheduler-operator-4-20-push.yaml, .tekton/kube-descheduler-operator-bundle-4-20-pull-request.yaml, .tekton/kube-descheduler-operator-bundle-4-20-push.yaml, bundle.Dockerfile, manifests/cluster-kube-descheduler-operator.clusterserviceversion.yaml
=> no-jira: Sync with release 4.20

.tekton/kube-descheduler-operator-bundle-main-pull-request.yaml, .tekton/kube-descheduler-operator-bundle-main-push.yaml, .tekton/kube-descheduler-operator-main-pull-request.yaml, .tekton/kube-descheduler-operator-main-push.yaml
=> no-jira: chore(.tekton): update to point to the main branch

.tekton/kube-descheduler-operator-bundle-main-pull-request.yaml, .tekton/kube-descheduler-operator-bundle-main-push.yaml, .tekton/kube-descheduler-operator-main-pull-request.yaml, .tekton/kube-descheduler-operator-main-push.yaml
=> chore(deps): update konflux references

renovate.json
=> feat: enable automatic dockerfile PR merging

renovate.json
=> experiment: update renovate.json to perhaps enable bundle.Dockerfile labeling
